In [ ]:
import numpy as np

In [ ]:
arr_d1=np.array([1,2,3])
print(arr_d1)

[1 2 3]


In [ ]:
arr_d2=np.array([[1,2,3],[4,5,6]])
print(arr_d2)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr_d3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr_d3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
arr=np.array(42)
arr_d1=np.array([1,2,3])
arr_d2=np.array([[1,2,3],[4,5,6]])
arr_d3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(arr.ndim)
print(arr_d1.ndim)
print(arr_d2.ndim)
print(arr_d3.ndim)


0
1
2
3


In [ ]:
zeros=np.zeros((2,3))
print(zeros)
ones=np.ones((3,3))
print((ones))
random_arr=np.random.random((2,2))
print(random_arr)
identity=np.eye(3)
print(identity)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.00202664 0.25290624]
 [0.4087888  0.40037887]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print("Shape: ",arr.shape)
print("Size: ",arr.size)
print("Data type: ",arr.dtype)
print("No.of dimensions: ",arr.ndim)



Shape:  (2, 3)
Size:  6
Data type:  int64
No.of dimensions:  2


In [ ]:
range_arr=np.arange(0,10,2)
print(range_arr)



[0 2 4 6 8]


In [ ]:
/*Create NumPy arrays
Create a 2D NumPy array named temp_data to represent the temperature readings from both greenhouses.
Print the array.
Check array properties
Print the shape, size, data type, and number of dimensions of temp_data.
Add a third greenhouse
The third greenhouse (GH3) records [21, 23, 22].
Create a new array updated_temp_data that includes all three greenhouses.
Generate supporting data
Create a zeros array (2×3) called sensor_error_flags to represent whether there were any sensor errors (0 means no error).
Create an identity matrix of size 3×3 named greenhouse_identity to uniquely identify each greenhouse.
Display all arrays
Print updated_temp_data, sensor_error_flags, and greenhouse_identity.*/

In [ ]:
import numpy as np

temp_data = np.array([[22, 25, 20],  [24, 26, 23]])
print("Initial temp_data array:")
print(temp_data)

print("\nShape of temp_data:", temp_data.shape)
print("Size of temp_data:", temp_data.size)
print("Data type of temp_data:", temp_data.dtype)
print("Number of dimensions of temp_data:", temp_data.ndim)

gh3_readings = np.array([[21, 23, 22]])
updated_temp_data = np.vstack((temp_data, gh3_readings))
print("\nupdated_temp_data array (All three greenhouses):")
print(updated_temp_data)


sensor_error_flags = np.zeros((2, 3), dtype=int)
print("\nsensor_error_flags array (2×3 zeros):")
print(sensor_error_flags)


greenhouse_identity = np.identity(3, dtype=int)
print("\ngreenhouse_identity matrix (3×3 identity):")
print(greenhouse_identity)


Initial temp_data array:
[[22 25 20]
 [24 26 23]]

Shape of temp_data: (2, 3)
Size of temp_data: 6
Data type of temp_data: int64
Number of dimensions of temp_data: 2

updated_temp_data array (All three greenhouses):
[[22 25 20]
 [24 26 23]
 [21 23 22]]

sensor_error_flags array (2×3 zeros):
[[0 0 0]
 [0 0 0]]

greenhouse_identity matrix (3×3 identity):
[[1 0 0]
 [0 1 0]
 [0 0 1]]


Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.
The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Your Tasks
Create the 2D NumPy array
Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.

In [ ]:
shipments=np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])
print("Apples shipped on Wednesday:",shipments[0][2])
print("Oranges shipped on Sunday:",shipments[1][6])
print("weekday shipments (Mon–Fri) APPLES:",shipments[0,0:5])
print("weekday shipments (Mon–Fri) ORANGES:",shipments[1,0:5])
print("weekend shipments (Sat & Sun) APPLES:",shipments[0,5:])
print("weekend shipments (Sat & Sun) ORANGES:",shipments[1,5:])
print("Apples from Wednesday to Saturday:",shipments[0,2:6])

shipments[0,5]=100
print("Shipments of apple(updated)",shipments[0])


Apples shipped on Wednesday: 55
Oranges shipped on Sunday: 75
weekday shipments (Mon–Fri) APPLES: [50 60 55 70 65]
weekday shipments (Mon–Fri) ORANGES: [40 45 50 60 55]
weekend shipments (Sat & Sun) APPLES: [80 90]
weekend shipments (Sat & Sun) ORANGES: [70 75]
Apples from Wednesday to Saturday: [55 70 65 80]
Shipments of apple(updated) [ 50  60  55  70  65 100  90]


In [ ]:
print("Arithematic operations")
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Addition:",a+b)
print("Element-wise multiplication:",a*b)
print("Scalar multiplication:",a*2)

print("Matrix multiplication:")
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[8,9],[6,7]])

print("BROADCASTING: Numpy automatically applies operations accross arrays of different shapes when compatible")
a=np.array([1,2,3])
b=np.array(2)
print(a+b)


Arithematic operations
Addition: [5 7 9]
Element-wise multiplication: [ 4 10 18]
Scalar multiplication: [2 4 6]
Matrix multiplication:
BROADCASTING: Numpy automatically applies operations accross arrays of different shapes when compatible
[3 4 5]


1. Arithmetic ufuncs
Operate element-wise on arrays.
np.add(x, y)
np.subtract(x, y)
np.multiply(x, y)
np.divide(x, y)
np.power(x, y)
np.mod(x, y)
🔹 2. Exponential and Logarithmic ufuncs
(You already covered these)
np.exp(x)
np.log(x)
np.log10(x)
np.log2(x)
np.expm1(x)    # exp(x) - 1
🔹 3. Trigonometric ufuncs
np.sin(x)
np.cos(x)
np.tan(x)
np.arcsin(x)
np.arccos(x)
np.arctan(x)
np.degrees(x)
np.radians(x)
🔹 4. Rounding ufuncs
np.round(x)
np.floor(x)
np.ceil(x)
np.trunc(x)
🔹 5. Statistical ufuncs
(Operate along an axis or entire array)
np.min(x)
np.max(x)
np.mean(x)
np.std(x)
np.var(x)
np.sum(x)
np.prod(x)
🔹 6. Logical ufuncs
np.logical_and(x, y)
np.logical_or(x, y)
np.logical_not(x)
np.logical_xor(x, y)
🔹 7. Comparison ufuncs
(Return Boolean arrays)
np.greater(x, y)
np.less(x, y)
np.equal(x, y)
np.not_equal(x, y)
np.greater_equal(x, y)
np.less_equal(x, y)
🔹 8. Bitwise ufuncs
(Operate on integers)
np.bitwise_and(x, y)
np.bitwise_or(x, y)
np.bitwise_xor(x, y)
np.invert(x)

In [ ]:
print("Aggregate functions")
arr=np.array([1,2,3,4,5,6])
print("Sum:",np.sum(arr))
print("Mean:",np.mean(arr))
print("Standard deviation:",np.std(arr))
print("Max:",np.max(arr))
print("Min:",np.min(arr))

Aggregate functions
Sum: 21
Mean: 3.5
Standard deviation: 1.707825127659933
Max: 6
Min: 1


In [ ]:
farmA=np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
farmB=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC=np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])
print("FarmA",farmA)
print("Farmb",farmB)
print("FarmC",farmC)


FarmA [[10 12 11]
 [ 9 11 10]
 [12 13 14]
 [ 8  7  9]]
Farmb [[20 19 21]
 [18 20 19]
 [22 23 21]
 [17 18 16]]
FarmC [[15 16 14]
 [14 13 15]
 [16 17 18]
 [12 11 13]]


You are a data engineer at a renewable-energy company that runs 3 solar farms.
Each farm has 4 solar panels, and each panel reports hourly energy production (kWh) for 3 hours during a test window.

Given data (raw)
Create arrays from these values:
production — shape (3 farms × 4 panels × 3 hours) represented as a 2D array per farm (you can stack/create as shown in tasks).
Farm A panels (rows = panels, cols = hours):


Tasks
Create arrays
Create three 2D NumPy arrays farmA, farmB, farmC (each shape (4,3)).
Stack them into a single 3D array production_all of shape (3, 4, 3).
Array attributes
Print the .shape, .size, .dtype, and .ndim of production_all.
Per-farm totals (arithmetic & aggregation)
Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).
Compute mean, std, and var per farm.
Per-hour matrix multiplication idea (matrix op)
For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).
Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)
Broadcasting adjustments
The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually).
Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
Compute a normalized version where you:
subtract the per-farm mean (use broadcasting),
divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.
Apply many ufuncs (use the ufuncs listed previously)
Apply the following element-wise operations (create variables for each) on the normalized data (or a copy) and show the resulting arrays (or summaries — shape/dtype/first row) where appropriate:
Exponential family: np.exp, np.expm1, np.log (note: handle non-positive inputs if needed), np.log10, np.log2.
Trigonometric: np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan, plus np.degrees, np.radians applied appropriately.
Rounding: np.round, np.floor, np.ceil, np.trunc.
Comparison & logical ufuncs: create a boolean mask high_output = production_all > 20 and apply np.logical_and, np.logical_or, np.logical_not, np.logical_xor combining masks (e.g., high_output and even_hours_mask). Also use comparison ufuncs like np.greater_equal, np.less.
Bitwise ufuncs (on integer arrays): create an integer array alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]]) for each farm (shape match required) — then apply np.bitwise_and, np.bitwise_or, np.invert where sensible.
Arithmetic ufuncs again: np.add, np.subtract, np.multiply, np.divide, np.power, np.mod.
Aggregations over ufunc outputs: e.g., np.sum(np.exp(...)), np.mean(np.sin(...)).
Broadcast-based summary table
Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.
Final KPIs (aggregation)
Compute:
overall_total (sum of all farms),
peak_hour value (max across hours) and which farm & panel produced it (use np.argmax with careful unraveling),
average_per_panel across all farms.

In [ ]:
import numpy as np

# Panel-hour data from your examples
farmA = np.array([
    [10, 12, 11],
    [9, 11, 10],
    [12, 13, 14],
    [8, 7, 9]
])
farmB = np.array([
    [20, 19, 21],
    [18, 20, 19],
    [22, 23, 21],
    [17, 18, 16]
])
farmC = np.array([
    [15, 16, 14],
    [14, 13, 15],
    [16, 17, 18],
    [12, 11, 13]
])

# Stack to shape (3, 4, 3) and force float dtype
production_all = np.stack([farmA, farmB, farmC], axis=0).astype(float)

# Array attributes
print("Shape:", production_all.shape)
print("Size:", production_all.size)
print("Data type:", production_all.dtype)
print("Dims:", production_all.ndim)

# Per-farm totals, mean, std, var
total_per_farm = production_all.sum(axis=(1, 2))
mean_per_farm = production_all.mean(axis=(1, 2))
std_per_farm = production_all.std(axis=(1, 2))
var_per_farm = production_all.var(axis=(1, 2))

print("Total per farm:", total_per_farm)
print("Mean per farm:", mean_per_farm)
print("Std per farm:", std_per_farm)
print("Var per farm:", var_per_farm)

# Weighted per-panel via dot
hour_weights = np.array([0.5, 1.0, 0.75])
weighted_per_panel = np.empty((3, 4))
for i in range(3):
    weighted_per_panel[i] = np.dot(production_all[i], hour_weights)
print("Weighted per panel (Farm A, first):", weighted_per_panel[0])

# Add +0.5 kWh offset to Farm B (broadcast, no recreate)
production_all_broadcasted = production_all.copy()
production_all_broadcasted[1] += 0.5
print("Sample broadcasted Farm B row:", production_all_broadcasted[1,0])

# Normalization (z-score per farm)
mean_bc = mean_per_farm[:, None, None]
std_bc = std_per_farm[:, None, None]
normalized = (production_all - mean_bc) / std_bc
print("Sample normalized (Farm A, panel 0):", normalized[0,0])

# Exponential/log family (first row)
exp_arr = np.exp(normalized)
expm1_arr = np.expm1(normalized)
log_arr = np.log(normalized.clip(min=1e-8) + 1)
log10_arr = np.log10(normalized.clip(min=1e-8) + 1)
log2_arr = np.log2(normalized.clip(min=1e-8) + 1)

# Trigonometric and angle conversions
sin_arr = np.sin(normalized)
cos_arr = np.cos(normalized)
tan_arr = np.tan(normalized)
arcsin_arr = np.arcsin(np.clip(normalized, -1, 1))
arccos_arr = np.arccos(np.clip(normalized, -1, 1))
arctan_arr = np.arctan(normalized)
degrees_arr = np.degrees(normalized)
radians_arr = np.radians(normalized)

# Rounding
round_arr = np.round(normalized)
floor_arr = np.floor(normalized)
ceil_arr = np.ceil(normalized)
trunc_arr = np.trunc(normalized)

# Comparison/logical ufuncs
high_output = production_all > 20
even_hours_mask = np.zeros_like(production_all, dtype=bool)
even_hours_mask[:, :, 0] = True
logical_and_arr = np.logical_and(high_output, even_hours_mask)
logical_or_arr = np.logical_or(high_output, even_hours_mask)
logical_not_arr = np.logical_not(high_output)
logical_xor_arr = np.logical_xor(high_output, even_hours_mask)
ge_arr = np.greater_equal(production_all, 15)
less_arr = np.less(production_all, 10)

# Bitwise ufuncs (integer mask)
alerts = np.array([
    [[1,0,1], [0,0,1], [1,1,0], [0,1,0]],
    [[1,0,1], [0,0,1], [1,1,0], [0,1,0]],
    [[1,0,1], [0,0,1], [1,1,0], [0,1,0]],
])
bitwise_and_arr = np.bitwise_and(production_all.astype(int), alerts)
bitwise_or_arr = np.bitwise_or(production_all.astype(int), alerts)
invert_arr = np.invert(alerts)

# Arithmetic ufuncs again
add_arr = np.add(production_all, 2)
subtract_arr = np.subtract(production_all, 2)
multiply_arr = np.multiply(production_all, 2)
divide_arr = np.divide(production_all, 2)
power_arr = np.power(production_all, 2)
mod_arr = np.mod(production_all, 2)

# Aggregations over ufunc outputs
sum_exp = np.sum(exp_arr)
mean_sin = np.mean(sin_arr)
print("Sum of exp(normalized):", sum_exp)
print("Mean of sin(normalized):", mean_sin)

# Broadcast-based summary: per-panel totals & needs_maintenance
panel_totals_per_farm = production_all.sum(axis=2)
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)
print("Per-panel totals, Farm A:", panel_totals_per_farm[0])
print("Needs maintenance (farm):", needs_maintenance)

# Final KPIs
overall_total = production_all.sum()
peak_val = np.max(production_all)
peak_idx = np.unravel_index(np.argmax(production_all), production_all.shape)
avg_per_panel = production_all.mean(axis=(0,1))
print("Overall total:", overall_total)
print("Peak value:", peak_val, "at", peak_idx)
print("Average per reading (all farms):", avg_per_panel)


Shape: (3, 4, 3)
Size: 36
Data type: float64
Dims: 3
Total per farm: [126. 234. 174.]
Mean per farm: [10.5 19.5 14.5]
Std per farm: [1.97905701 1.97905701 1.97905701]
Var per farm: [3.91666667 3.91666667 3.91666667]
Weighted per panel (Farm A, first): [25.25 23.   29.5  17.75]
Sample broadcasted Farm B row: [20.5 19.5 21.5]
Sample normalized (Farm A, panel 0): [-0.25264558  0.75793673  0.25264558]
Sum of exp(normalized): 57.55695815214101
Mean of sin(normalized): 6.1679056923619804e-18
Per-panel totals, Farm A: [33. 30. 39. 24.]
Needs maintenance (farm): [ True False  True]
Overall total: 534.0
Peak value: 23.0 at (np.int64(1), np.int64(2), np.int64(1))
Average per reading (all farms): [14.41666667 15.         15.08333333]


In [ ]:
print("Reshaping")
arr=np.array([1,2,3,4,5,6])
print("Before reshaping")
print(arr)
reshaped=arr.reshape(2,3)
print("After reshaping")
print(reshaped)


Reshaping
Before reshaping
[1 2 3 4 5 6]
After reshaping
[[1 2 3]
 [4 5 6]]


In [ ]:
print("Stacking and splitting")
a=np.array([1,2])
b=np.array([3,4])

print("Vertical stack")
print(np.vstack((a,b)))

print("Horizontal stack")
print(np.hstack((a,b)))


print("\n")
print("Splitting")
arr=np.array([1,2,3,4,5])

print("Split into three parts")
print(np.array_split(arr,3))

Stacking and splitting
Vertical stack
[[1 2]
 [3 4]]
Horizontal stack
[1 2 3 4]


Splitting
Split into three parts
[array([1, 2]), array([3, 4]), array([5])]


In [ ]:
print("Advanced Indexing")
print("Boolean indexing")
arr=np.array([1,2,3,4,5])
print(arr[arr>3])

print("Fancy indexing")
arr=np.array([10,20,30,40])
indices=[0,2]
print(arr[indices])

Advanced Indexing
Boolean indexing
[4 5]
Fancy indexing
[10 30]


In [ ]:
print("Copy vs View")
print("View share memory")
arr=np.array([1,2,3])
veiw=arr.view()
veiw[0]=10
print(arr)

print("Copy does not share memory")
copy=arr.copy()
copy[0]=10
print(arr)

Copy vs View
View share memory
[10  2  3]
Copy does not share memory
[10  2  3]


In [ ]:
print("Saving and loading")
print("Save to a file")
arr=np.array([1,2,3])
np.save('array.npy',arr)

print("Load from a file")
loaded_arr=np.load('array.npy')
print(loaded_arr)

Saving and loading
Save to a file
Load from a file
[1 2 3]


TasksArray Creation
Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.
Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.

In [ ]:
arr=np.arange(10,51,1)
print(arr)
random_arr=np.random.random((3,3))
print(random_arr)
print("Array attributes:")
print("Shape:",arr.shape)
print("Size:",arr.size)
print("Data type:",arr.dtype)
print("Adding 5 to every element in arr")
arr=np.add(arr,5)
print(arr)
arr1=np.array([[1,2,3],[3,4,5]])
arr2=np.array([[0,9,8],[7,6,5]])
print("Multiplying two 2d arrays element-wise")
print(arr1*arr2)
print("5D array")
arr5D=np.arange(1,26).reshape(5,5)
print(arr5D)
print("The first row:",arr5D[0])
print("The last colum:",arr5D[:,4])
print("A subarray of the first three rows and first two columns:",arr5D[:3,:2])
print("Creating a 10-element array of random integers between 10 and 100")






[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0.40533761 0.24750348 0.22961526]
 [0.73598107 0.96161319 0.69796327]
 [0.22921583 0.06293766 0.06885538]]
Array attributes:
Shape: (41,)
Size: 41
Data type: int64
Adding 5 to every element in arr
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
Multiplying two 2d arrays element-wise
[[ 0 18 24]
 [21 24 25]]
5D array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
The first row: [1 2 3 4 5]
The last colum: [ 5 10 15 20 25]
A subarray of the first three rows and first two columns: [[ 1  2]
 [ 6  7]
 [11 12]]


In [ ]:
import random
print("Creating a 10-element array of random integers between 10 and 100")
ran_arr=[random.randint(10,100) for _ in range(10)]
print(ran_arr)
print("Minimum value:",np.min(ran_arr))
print("Maximum value:",np.max(ran_arr))
print("Mean:",np.mean(ran_arr))
print("Standard deviation:",np.std(ran_arr))

print("Reshaping:")
reshape_arr=np.arange(1,13).reshape(3,4)
print(reshape_arr)

print("Broadcasting")
ones=np.ones((3,3))
print(ones)
print("Adding [1,2,3] to each row")
add_ones=np.add(ones,[1,2,3])
print(add_ones)


Creating a 10-element array of random integers between 10 and 100
[78, 89, 37, 42, 88, 90, 40, 81, 91, 52]
Minimum value: 37
Maximum value: 91
Mean: 68.8
Standard deviation: 21.894291493446413
Reshaping:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Broadcasting
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Adding [1,2,3] to each row
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
